#!/bin/bash

# WalSmart Ngrok Setup Script
# This script helps you expose your local WalSmart app to the internet

echo "🚀 WalSmart Ngrok Setup"
echo "======================="
echo ""

# Check if ngrok is installed
if ! command -v ngrok &> /dev/null; then
    echo "❌ ngrok is not installed. Installing now..."
    brew install ngrok
    echo "✅ ngrok installed!"
fi

echo "📡 Starting ngrok tunnels..."
echo ""

# Kill any existing ngrok processes
pkill ngrok 2>/dev/null

# Start ngrok for backend (port 8000) in the background
echo "🔧 Starting backend tunnel (port 8000)..."
ngrok http 8000 --log=stdout > /tmp/ngrok-backend.log &
BACKEND_PID=$!

# Wait for ngrok to start
sleep 3

# Get the ngrok URL for backend
BACKEND_URL=$(curl -s http://localhost:4040/api/tunnels | grep -o '"public_url":"[^"]*' | grep -o 'https://[^"]*' | head -n 1)

if [ -z "$BACKEND_URL" ]; then
    echo "❌ Failed to get backend ngrok URL"
    exit 1
fi

echo "✅ Backend URL: $BACKEND_URL"
echo ""

# Create .env file with the backend URL
cat > project/.env << EOF
# Backend API URL - Auto-generated by ngrok setup
VITE_API_URL=$BACKEND_URL
EOF

echo "📝 Created project/.env with backend URL"
echo ""

# Now start ngrok for frontend (port 5173) in new terminal
echo "🌐 Starting frontend tunnel (port 5173)..."
osascript -e 'tell app "Terminal" to do script "cd '$(pwd)' && ngrok http 5173"'

# Wait a bit for the second ngrok to start
sleep 3

# Try to get frontend URL (it will be on a different port, usually 4041)
FRONTEND_URL=$(curl -s http://localhost:4041/api/tunnels 2>/dev/null | grep -o '"public_url":"[^"]*' | grep -o 'https://[^"]*' | head -n 1)

echo ""
echo "========================================="
echo "✨ Setup Complete!"
echo "========================================="
echo ""
echo "📱 Share this URL with anyone:"
if [ -n "$FRONTEND_URL" ]; then
    echo "   $FRONTEND_URL"
else
    echo "   Check the new terminal window for your frontend URL"
fi
echo ""
echo "🔧 Backend URL (saved to .env):"
echo "   $BACKEND_URL"
echo ""
echo "⚠️  Important:"
echo "   1. Restart your Vite dev server (Ctrl+C and run 'npm run dev' again)"
echo "   2. Your app will now work from anywhere!"
echo ""
echo "🛑 To stop ngrok tunnels:"
echo "   Run: pkill ngrok"
echo ""
